config/routes.rb
Rails.application.routes.draw do
  get 'services/solar_introduction'
  get 'services/solar_water_heater'
  get 'services/solar_street_light'
  get 'services/solar_power_plant'
  get 'services/solar_structure'


  get 'project/index'

  get 'welcome/index'
  root 'welcome#index'
  get 'welcome/aboutus'
  get 'welcome/career'
  get 'welcome/service'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users

 resources :quotes, only: [:create] do 
    # collection do
    #   post :quotes
    # end
  end 

  post 'welcome/company_update'
  resources :project, only:[:index,:show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/about.rb
class About < ApplicationRecord
	mount_uploader :about_image, AboutUploader
	mount_uploader :mission_image, AboutUploader
	mount_uploader :vision_image, AboutUploader
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/company_heading.rb
class CompanyHeading < ApplicationRecord
end

app/models/company_info.rb
class CompanyInfo < ApplicationRecord
	mount_uploader :image, ImageUploader
end

app/models/company_update.rb
class CompanyUpdate < ApplicationRecord
end

app/models/image.rb
class Image < ApplicationRecord
	# has_many :upload_images

	mount_uploader :upload_image, ImageUploader
	# has_many :select_images
	# has_many :select_images, through: :images



end

app/models/news.rb
class News < ApplicationRecord

	def project_image
		if self.project_id.present?
			project = Project.find(self.project_id)
			pro_image = project.images.first.data
			return pro_image
		else
			return ""
		end	
	end
end

app/models/project.rb
class Project < ApplicationRecord
has_many :news,:dependent => :delete_all
has_many :project_images
has_many :images, through: :project_images,:dependent => :delete_all
extend FriendlyId
  friendly_id :name, use: [:slugged, :finders]
end

app/models/project_category.rb
class ProjectCategory < ApplicationRecord
end

app/models/project_image.rb
class ProjectImage < ApplicationRecord
	mount_uploader :upload_image, ImageUploader	
	belongs_to :project
	belongs_to :image
end

app/models/quote.rb
class Quote < ApplicationRecord
	validates :mob_no, :presence => {:message => 'number only 10 digit'},
                     :numericality => true,
                     :length => { :minimum => 10, :maximum => 15 }
end

app/models/service.rb
class Service < ApplicationRecord
	has_many :service_images
	has_many :service_icons, through: :service_images,:dependent => :delete_all

  scope :active, -> {where(is_active: true)}

end

app/models/service_icon.rb
class ServiceIcon < ApplicationRecord
	mount_uploader :image, ImageUploader
end

app/models/service_image.rb
class ServiceImage < ApplicationRecord
	mount_uploader :image, ImageUploader	
	belongs_to :service
	belongs_to :service_icon
end

app/models/social_link.rb
class SocialLink < ApplicationRecord
end

app/models/team.rb
class Team < ApplicationRecord
	mount_uploader :image, ImageUploader
end

app/models/testimonial.rb
class Testimonial < ApplicationRecord
	mount_uploader :client_image , ImageUploader


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	
  def index
  	@quote = Quote.new
  	@projects = Project.all
  	@news = News.all
  	@teams = Team.all
  	@project_categories = ProjectCategory.all
    @testimonials = Testimonial.order("RANDOM()").limit(3)
    @services = Service.active.order("updated_at DESC")
    @company_info = CompanyInfo.all.order("updated_at DESC").last
    @company_heading = CompanyHeading.all.order("updated_at DESC").last
  end  


  def aboutus
    @aboutus = About.all.last
    @services = Service.all.order("updated_at DESC")
    @project_categories = ProjectCategory.order("RANDOM()").limit(3)
    @company_info = CompanyInfo.all.order("updated_at DESC").last
  	
  end

  def career
    
  end

  def company_update
    @company_update = CompanyUpdate.new(email: params[:company_update][:email])
    if @company_update.save
      flash[:success] = "Thanks for registering for News Letter"
    else
      flash.now[:error] = "Sorry! Your action is not working!"
    end
  end


end

app/helpers/project_helper.rb
module ProjectHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/_service.html.erb
<section class="services" id="service">
    <div class="container">
    <div class="row">
        <a href="/welcome/service">
            <div class="sub-title text-center">Our Services</div>
            <h1 class="text-center">What We Do</h1>
        </a>

        <div class="col-md-3 col-sm-3 col-xs-6">
          <div class="service ">
            <img src="<%= asset_path("data:image/png;base64,#{Base64.encode64(Service.find(1).service_icons.first.data
                ).gsub("\n", "")}")%>" class="img-responsive" />
            <a><p>SOLAR SECTION:</p></a>
            <span class="white">
              <ul>
                <li><%= link_to "Solar Introduction", services_solar_introduction_path %></li>
                <li><%= link_to "Solar Water Heater", services_solar_water_heater_path %></li>
                <li><%= link_to "Solar Street Light", services_solar_street_light_path %></li>
                <li><%= link_to "Solar Power Plant", services_solar_power_plant_path %></li>
                <li><%= link_to "Solar Structure", services_solar_structure_path %></li>
              </ul>
            </span>
          </div>
        </div>

        <% Service.active.order("updated_at DESC").each do |svs| %>
        <div class="col-md-3 col-sm-3 col-xs-6">
          <div class="service ">
            <a href="/welcome/service">
              <img src="<%= asset_path("data:image/png;base64,#{Base64.encode64(svs.service_icons.first.data
                    ).gsub("\n", "")}")%>" class="img-responsive" />
              <p><%= svs.title %></p>
              <span class="white"><%= raw svs.description %></span>
            </a>
          </div>
        </div>
        <%end%>
    </div>
</section>
<style type="text/css">
  a, a:hover{color: #fff;}
  span.white{color:white;}
</style>

app/views/welcome/career.html.erb
<div class="inner_header"> 
       <img class="img-responsive" src="<%= asset_path("slider.png")%>">
      <div class="right_text_wrap">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-12 col-xs-12 mid_contnt">
                  <div class="mid_heading"><span class="colored-text">Engineering</span> Your Dreams With Us<span class="colored-text">.</span></div>
                  <div class="mid-sub-title text-center">Constructions And Building</div>
               </div>
            </div>
            <div class="row">
               <div class="col-md-12 col-sm-12 col-xs-12 text-center">
                   <div class="header-button">
                     <button type="button" class="btn btn-default">Our Story</button>
                     <!-- <a href="#Quote"><button type="button" class="btn btn-default active">Get a Quote</button></a> -->
                     
                  </div>
               </div>
            </div>
         </div>
      </div>   
</div>
<div style="text-align: center;">
    <h2>Coming soon.....</h2>
</div>

app/views/welcome/company_update.js.erb
<%if params[:controller] == "quotes"%>
	$('#flash').html("<%= j render partial: 'layouts/message' %>");
	$("form")[0].reset();
<%else%>
	$('#flash1').html("<%= j render partial: 'layouts/message' %>");
	$("form")[1].reset();
<%end%>	

app/views/welcome/service.html.erb
<div class="inner_header"> 
       <img class="img-responsive" src="<%= asset_path("slider.png")%>">
      <div class="right_text_wrap">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-12 col-xs-12 mid_contnt">
                  <div class="mid_heading"><span class="colored-text">Engineering</span> Your Dreams With Us<span class="colored-text">.</span></div>
                  <div class="mid-sub-title text-center">Constructions And Building</div>
               </div>
            </div>
            <div class="row">
               <div class="col-md-12 col-sm-12 col-xs-12 text-center">
                   <div class="header-button">
                     <button type="button" class="btn btn-default">Our Story</button>
                     <!-- <a href="#Quote"><button type="button" class="btn btn-default active">Get a Quote</button></a> -->
                     
                  </div>
               </div>
            </div>
         </div>
      </div>   
</div>
<%=render "service" ,services: Service.all.order("updated_at DESC")%>