config/routes.rb
Rails.application.routes.draw do
  get 'services/solar_introduction'
  get 'services/solar_water_heater'
  get 'services/solar_street_light'
  get 'services/solar_power_plant'
  get 'services/solar_structure'


  get 'project/index'

  get 'welcome/index'
  root 'welcome#index'
  get 'welcome/aboutus'
  get 'welcome/career'
  get 'welcome/service'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users

 resources :quotes, only: [:create] do 
    # collection do
    #   post :quotes
    # end
  end 

  post 'welcome/company_update'
  resources :project, only:[:index,:show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/about.rb
class About < ApplicationRecord
	mount_uploader :about_image, AboutUploader
	mount_uploader :mission_image, AboutUploader
	mount_uploader :vision_image, AboutUploader
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_color.rb
class ApplicationColor < ApplicationRecord
end

app/models/company_heading.rb
class CompanyHeading < ApplicationRecord
end

app/models/company_info.rb
class CompanyInfo < ApplicationRecord
	mount_uploader :image, ImageUploader
end

app/models/company_update.rb
class CompanyUpdate < ApplicationRecord
end

app/models/image.rb
class Image < ApplicationRecord
	# has_many :upload_images

	mount_uploader :upload_image, ImageUploader
	# has_many :select_images
	# has_many :select_images, through: :images



end

app/models/news.rb
class News < ApplicationRecord

	def project_image
		if self.project_id.present?
			project = Project.find(self.project_id)
			pro_image = project.images.first.data
			return pro_image
		else
			return ""
		end	
	end
end

app/models/project.rb
class Project < ApplicationRecord
has_many :news,:dependent => :delete_all
has_many :project_images
has_many :images, through: :project_images,:dependent => :delete_all
extend FriendlyId
  friendly_id :name, use: [:slugged, :finders]
end

app/models/project_category.rb
class ProjectCategory < ApplicationRecord
end

app/models/project_image.rb
class ProjectImage < ApplicationRecord
	mount_uploader :upload_image, ImageUploader	
	belongs_to :project
	belongs_to :image
end

app/models/quote.rb
class Quote < ApplicationRecord
	validates :mob_no, :presence => {:message => 'number only 10 digit'},
                     :numericality => true,
                     :length => { :minimum => 10, :maximum => 15 }
end

app/models/service.rb
class Service < ApplicationRecord
	has_many :service_images
	has_many :service_icons, through: :service_images,:dependent => :delete_all

  scope :active, -> {where(is_active: true)}

end

app/models/service_icon.rb
class ServiceIcon < ApplicationRecord
	mount_uploader :image, ImageUploader
end

app/models/service_image.rb
class ServiceImage < ApplicationRecord
	mount_uploader :image, ImageUploader	
	belongs_to :service
	belongs_to :service_icon
end

app/models/social_link.rb
class SocialLink < ApplicationRecord
end

app/models/team.rb
class Team < ApplicationRecord
	mount_uploader :image, ImageUploader
end

app/models/testimonial.rb
class Testimonial < ApplicationRecord
	mount_uploader :client_image , ImageUploader


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/project_controller.rb
class ProjectController < ApplicationController
  def index
  	@projects = Project.all
 	@project_categories = ProjectCategory.all
  end

  def show
  	@projects = Project.all
  	@project = Project.find(params[:id])
  	@project_images = @project.images
  	@outher_projects = @projects.where.not(id: @project.id).order('created_at DESC').limit(4)
  end
end

app/helpers/project_helper.rb
module ProjectHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/project/index.html.erb
<div class="inner_header"> 
       <img class="img-responsive" src="<%= asset_path("slider.png")%>">
      <div class="right_text_wrap">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-12 col-xs-12 mid_contnt">
                  <div class="mid_heading"><span class="colored-text">Engineering</span> Your Dreams With Us<span class="colored-text">.</span></div>
                  <div class="mid-sub-title text-center">Constructions And Building</div>
               </div>
            </div>
            <div class="row">
               <div class="col-md-12 col-sm-12 col-xs-12 text-center">
                   <div class="header-button">
                     <button type="button" class="btn btn-default">Our Story</button>
                     <!-- <a href="#Quote"><button type="button" class="btn btn-default active">Get a Quote</button></a> -->
                     
                  </div>
               </div>
            </div>
         </div>
      </div>   
    </div>
   <section class="gallery">
       <div class="container">
          <div class="main">
            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12 text-center">
                  <div class="sub_titl">Professional Work</div>
                  <h2 class="projcts">Our Projects</h2>
               </div>
                <div class="col-md-12 col-sm-12 col-xs-12 text-center">
               <div id="myBtnContainer">
                  <button class="btn active" onclick="filterSelection('all')"> Show all</button>
                  <% @project_categories.each do |category|%>  
                  <button class="btn" onclick="filterSelection('<%=category.name%>')"> <%=category.name%></button>
                  <%end%>
                  <!-- <button class="btn" onclick="filterSelection('nature')"> Construction</button>
                  <button class="btn" onclick="filterSelection('cars')">Architecture</button>
                  <button class="btn" onclick="filterSelection('people')"> Modern</button> -->
               </div>
                </div>
            </div>
         <div class="row">
          <% @projects.each do |project|%>
          <%#project.images.each do |image|%>
            <div class="col-md-4 col-sm-4 col-xs-4 column <%=project.try(:project_type)%>">
              <div class="content">
                <a href="<%=project_path(project)%>"><img src="<%= asset_path("data:image/png;base64,#{Base64.encode64(project.images.first.data).gsub("\n", "")}")%>" alt="Mountains" style="width:100%"></a>
              </div>
            </div>
          <%#end%>
        <%end%> 
          </div>
           
            </div>
         </div>      
   </section>
   <script type="text/javascript">
   filterSelection("all")
   $('.active-class').addClass('active');
   function filterSelection(c) {
     $('.active-class').removeClass('active');
     var x, i;
     x = document.getElementsByClassName("column");
     if (c == "all") c = "";
     for (i = 0; i < x.length; i++) {
       w3RemoveClass(x[i], "show");
       if (x[i].className.indexOf(c) > -1) w3AddClass(x[i], "show");
     }
   }

   function w3AddClass(element, name) {
     var i, arr1, arr2;
     arr1 = element.className.split(" ");
     arr2 = name.split(" ");
     for (i = 0; i < arr2.length; i++) {
       if (arr1.indexOf(arr2[i]) == -1) {element.className += " " + arr2[i];}
     }
   }

   function w3RemoveClass(element, name) {
     var i, arr1, arr2;
     arr1 = element.className.split(" ");
     arr2 = name.split(" ");
     for (i = 0; i < arr2.length; i++) {
       while (arr1.indexOf(arr2[i]) > -1) {
         arr1.splice(arr1.indexOf(arr2[i]), 1);     
       }
     }
     element.className = arr1.join(" ");
   }


   // Add active class to the current button (highlight it)
   var btnContainer = document.getElementById("myBtnContainer");
   var btns = btnContainer.getElementsByClassName("btn");
   for (var i = 0; i < btns.length; i++) {
     btns[i].addEventListener("click", function(){
       var current = document.getElementsByClassName("active");
       current[0].className = current[0].className.replace(" active", "");
       this.className += " ";
     });
   }
</script>

app/views/project/index1.html.erb
<div class="inner_header"> 
       <img class="img-responsive" src="<%= asset_path("slider.png")%>">
      <div class="right_text_wrap">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-12 col-xs-12 mid_contnt">
                  <div class="mid_heading"><span class="colored-text">Engineering</span> Your Dreams With Us<span class="colored-text">.</span></div>
                  <div class="mid-sub-title text-center">Constructions And Building</div>
               </div>
            </div>
            <div class="row">
               <div class="col-md-12 col-sm-12 col-xs-12 text-center">
                   <div class="header-button">
                     <button type="button" class="btn btn-default">Our Story</button>
                     <!-- <a href="#Quote"><button type="button" class="btn btn-default active">Get a Quote</button></a> -->
                     
                  </div>
               </div>
            </div>
         </div>
      </div>   
    </div>
<section class="gallery-sliders">
   <div class="container">
      <div class="row">
         <div class="col-md-6 col-sm-6 col-xs-12">
            <div class="flexslider">
               <ul class="slides">
                  <li>
                     <img src="<%=asset_path "slider1.png"%>" />
                  </li>
                  <li>
                     <img src="<%=asset_path "slider2.png" %>" />
                  </li>
                  <li>
                     <img src="<%=asset_path "slider3.png" %>" />
                  </li>
                  <li>
                     <img src="<%=asset_path "slider4.png" %>" />
                  </li>
               </ul>
            </div>
         </div>
         <!--<div class="col-md-3 col-sm-3 col-xs-12">
            <ul class="slides-content">
            <li>
            <img src="<%=asset_path "slider1.png"%>" />
            <h6>MMR Group</h6>
            </li>
            <li>
            <img src="<%=asset_path "slider2.png" %>" />
            <h6>MMR Group</h6>
            </li>
            </ul>
            </div>
            <div class="col-md-3 col-sm-3 col-xs-12">
            <ul class="slides-content">
            <li>
            <img src="<%=asset_path "slider1.png"%>" />
            <h6>MMR Group</h6>
            </li>
            <li>
            <img src="<%=asset_path "slider2.png" %>" />
            <h6>MMR Group</h6>
            </li>
            </ul>
            </div>--->
         <div class="col-md-6 col-sm-6 col-xs-12">
            <div class="contact-map">
               <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d56028.2556664276!2d77.25191712354282!3d28.636775131468987!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x390cfb5614d9cee3%3A0x1a739c7ab9cd4710!2sNirman+Vihar!5e0!3m2!1sen!2sin!4v1484562677939"></iframe>
            </div>
         </div>
      </div>
      <div class="row">
         <div  class="project-content">
            <div class="col-md-3 col-sm-3 col-xs-12">
               <ul class="content-list">
                  <li><span class="colored-txt"><img src="<%=asset_path "project-name.png" %>">Name of the Project :</span> Partap Infotech</li>
                  <li><span class="colored-txt"><img src="<%=asset_path "location.png" %>">Location : </span>Noida</li>
               </ul>
            </div>
            <div class="col-md-3 col-sm-3 col-xs-12">
               <ul class="content-list">
                  <li><span class="colored-txt"><img src="<%=asset_path "client.png" %>">Client : </span>Forum Projects Ltd.</li>
                  <li><span class="colored-txt"><img src="<%=asset_path "archtect.png" %>">Architect : </span> Arc 10 Studio</li>
               </ul>
            </div>
            <div class="col-md-3 col-sm-3 col-xs-12">
               <ul class="content-list">
                  <li><span class="colored-txt"><img src="<%=asset_path "construct.png" %>">Consultant : </span> BES Facade Consultant</li>
                  <li><span class="colored-txt"><img src="<%=asset_path "type.png" %>">Type : </span> Commercial</li>
               </ul>
            </div>
            <div class="col-md-3 col-sm-3 col-xs-12">
               <ul class="content-list inline-txt">
                  <li><span class="colored-txt"><img src="<%=asset_path "total.png" %>">Total sq. m :</span> 32000 sqm</li>
                  <li><span class="colored-txt"><img src="<%=asset_path "floor.png" %>">Floor : </span> 38</li>
               </ul>
            </div>
         </div>
      </div>
   </div>
</section>

<section class="crousal-slide">
   <div class="container">
      <div class="row">
         <h2 class="text-center projcts">Other Projects</h2>
         <div class="projects-slide-list">
            <div class="col-md-3 col-sm-3 col-xs-12">
               <div class="other-projects">
                  <img src="<%=asset_path "craousl1.png" %>" class="img-responsive"/>
               </div>
            </div>
            <div class="col-md-3 col-sm-3 col-xs-12">
               <div class="other-projects">
                  <img src="<%=asset_path "craousl2.png" %>" class="img-responsive"/>
               </div>
            </div>
            <div class="col-md-3 col-sm-3 col-xs-12">
               <div class="other-projects">
                  <img src="<%=asset_path "craousl3.png" %>" class="img-responsive"/>
               </div>
            </div>
            <div class="col-md-3 col-sm-3 col-xs-12">
               <div class="other-projects">
                  <img src="<%=asset_path "craousl4.png" %>" class="img-responsive"/>
               </div>
            </div>
         </div>
      </div>
   </div>
</section>

<!----------------------------------------------->
  
<script type="text/javascript">
  $(function() {
    $('.flexslider').flexslider({
       animation: "slide"
     });
  })
</script>

app/views/project/show.html.erb
<div class="inner_header"> 
       <img class="img-responsive" src="<%= asset_path("slider.png")%>">
      <div class="right_text_wrap">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-12 col-xs-12 mid_contnt">
                  <div class="mid_heading"><span class="colored-text">Engineering</span> Your Dreams With Us<span class="colored-text">.</span></div>
                  <div class="mid-sub-title text-center">Constructions And Building</div>
               </div>
            </div>
            <div class="row">
               <div class="col-md-12 col-sm-12 col-xs-12 text-center">
                   <div class="header-button">
                     <button type="button" class="btn btn-default">Our Story</button>
                     <!-- <a href="#Quote"><button type="button" class="btn btn-default active">Get a Quote</button></a> -->
                     
                  </div>
               </div>
            </div>
         </div>
      </div>   
    </div>
<section class="gallery-sliders">
   <div class="container">
      <div class="row">
         <div class="col-md-6 col-sm-6 col-xs-12">
            <div class="flexslider">
               <ul class="slides">
                 <%@project_images.each do |image|%> 
                     <li>
                        <img src="<%= asset_path("data:image/png;base64,#{Base64.encode64(image.data).gsub("\n", "")}")%>" alt="Mountains" style="width:100%">
                     </li>
                     <!-- <li>
                        <img src="<%#=asset_path "slider2.png" %>" />
                     </li>
                     <li>
                        <img src="<%#=asset_path "slider3.png" %>" />
                     </li>
                     <li>
                        <img src="<%#=asset_path "slider4.png" %>" />
                     </li> -->
                  <% end -%>
               </ul>
            </div>
         </div>
         <!--<div class="col-md-3 col-sm-3 col-xs-12">
            <ul class="slides-content">
            <li>
            <img src="<%=asset_path "slider1.png"%>" />
            <h6>MMR Group</h6>
            </li>
            <li>
            <img src="<%=asset_path "slider2.png" %>" />
            <h6>MMR Group</h6>
            </li>
            </ul>
            </div>
            <div class="col-md-3 col-sm-3 col-xs-12">
            <ul class="slides-content">
            <li>
            <img src="<%=asset_path "slider1.png"%>" />
            <h6>MMR Group</h6>
            </li>
            <li>
            <img src="<%=asset_path "slider2.png" %>" />
            <h6>MMR Group</h6>
            </li>
            </ul>
            </div>--->
         <div class="col-md-6 col-sm-6 col-xs-12">
            <div class="contact-map">
               <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d56028.2556664276!2d77.25191712354282!3d28.636775131468987!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x390cfb5614d9cee3%3A0x1a739c7ab9cd4710!2sNirman+Vihar!5e0!3m2!1sen!2sin!4v1484562677939"></iframe>
            </div>
         </div>
      </div>
      <div class="row">
         <div  class="project-content">
            <div class="col-md-3 col-sm-3 col-xs-12">
               <ul class="content-list">
                  <li><span class="colored-txt"><img src="<%=asset_path "project-name.png" %>">Name of the Project :</span> <%=@project.try(:name)%></li>
                  <li><span class="colored-txt"><img src="<%=asset_path "location.png" %>">Location : </span><%=@project.try(:address)%></li>
               </ul>
            </div>
            <div class="col-md-3 col-sm-3 col-xs-12">
               <ul class="content-list">
                  <li><span class="colored-txt"><img src="<%=asset_path "client.png" %>">Client : </span><%=@project.try(:client)%></li>
                  <li><span class="colored-txt"><img src="<%=asset_path "archtect.png" %>">Architect : </span> <%=@project.try(:architect)%></li>
               </ul>
            </div>
            <div class="col-md-3 col-sm-3 col-xs-12">
               <ul class="content-list">
                  <li><span class="colored-txt"><img src="<%=asset_path "construct.png" %>">Consultant : </span> <%=@project.try(:consultant)%></li>
                  <li><span class="colored-txt"><img src="<%=asset_path "type.png" %>">Type : </span><%=@project.try(:project_type)%> </li>
               </ul>
            </div>
            <div class="col-md-3 col-sm-3 col-xs-12">
               <ul class="content-list inline-txt">
                  <li><span class="colored-txt"><img src="<%=asset_path "total.png" %>">Total sq. m :</span> <%=@project.try(:total_sq_m)%></li>
                  <li><span class="colored-txt"><img src="<%=asset_path "floor.png" %>">Floor : </span> <%=@project.try(:floor)%></li>
               </ul>
            </div>
         </div>
      </div>
   </div>
</section>

<section class="crousal-slide">
   <div class="container">
      <div class="row">
         <h2 class="text-center projcts">Other Projects</h2>
         <div class="projects-slide-list">
            <%@outher_projects.each do |project|%>
                  <div class="col-md-3 col-sm-3 col-xs-12">
                     <div class="other-projects">
                        <a href="<%=project_path(project)%>"><img src="<%= asset_path("data:image/png;base64,#{Base64.encode64(project.images.first.data).gsub("\n", "")}")%>" alt="Mountains" style="width:100%" class="img-responsive">
                        </a>
                     </div>
                  </div>
            <% end -%>      
                  <!-- <div class="col-md-3 col-sm-3 col-xs-12">
                     <div class="other-projects">
                        <img src="<%=asset_path "craousl2.png" %>" class="img-responsive"/>
                     </div>
                  </div>
                  <div class="col-md-3 col-sm-3 col-xs-12">
                     <div class="other-projects">
                        <img src="<%=asset_path "craousl3.png" %>" class="img-responsive"/>
                     </div>
                  </div>
                  <div class="col-md-3 col-sm-3 col-xs-12">
                     <div class="other-projects">
                        <img src="<%=asset_path "craousl4.png" %>" class="img-responsive"/>
                     </div>
                  </div> -->
         </div>
      </div>
   </div>
</section>

<!----------------------------------------------->
  
<script type="text/javascript">
  $(function() {
    $('.flexslider').flexslider({
       animation: "slide"
     });
  })
</script>